name: Build docs

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
         submodules: true
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          components: rust-src
          override: true
      - name: Generate documentation
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: -Z build-std=core,alloc,panic_abort -Z build-std-features=compiler-builtins-mem --target x86_64-unknown-hermit-kernel.json
      - name: Generate index.html
        run: |
          cat > target/x86_64-unknown-hermit-kernel/doc/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>Redirect!</title>
              <meta http-equiv="refresh" content="0; url=https://hermitcore.github.io/libhermit-rs/hermit/" />
            </head>
            <body>
              <p><a href="https://hermitcore.github.io/libhermit-rs/hermit/">Redirect</a></p>
            </body>
          </html>
          EOL
      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: target/x86_64-unknown-hermit-kernel/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
